name: Trigger website deployment

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger lluisalemanypuig.github.io deployment
        env:
          GH_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN__QR_GENERATOR }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/lluisalemanypuig/lluisalemanypuig.github.io/dispatches \
            -f event_type='deploy-qr-generator'
